apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kotlinapp
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 4