apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kotlin-app-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kotlin-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
